### PR TITLE
Add app

### PR DESCRIPTION
**Pull request by teslor**

### CODE REVIEW

**Comment by patleeman** [comment]
Cool project @teslor.

I think it would make sense to break out a new section called `Projects using Quill.js` instead of lumping this into other.  Thoughts @jhchen?

**Comment by teslor** [comment]
Thanks @patleeman. At first I wanted to create "Applications" section, however in this case this app would be the only one there, so I placed it into "Other".

**Comment by patleeman** [comment]
@teslor That makes sense. If we see other applications being added we can split off an applications section then.

**Comment by jhchen** [comment]
@patleeman I agree we can just see how long the list goes and address it then

**Pull request merged**
